import js from '@eslint/js';
import ts from 'typescript-eslint';
import prettierConfigRecommended from 'eslint-plugin-prettier/recommended';
import reactPlugin from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import nextPlugin from '@next/eslint-plugin-next';

import globals from 'globals';

import { fixupPluginRules } from '@eslint/compat';

export default [
    {
        files: ['** / *.{js,jsx,ts,tsx}'],
        rules: {
            ...js.configs.recommended.rules,
        },
    },
    ...ts.configs.recommended,
    {
        files: ['pages/api/**/*'],
        languageOptions: {
            globals: globals.node,
        },
    },
    {
        languageOptions: {
            globals: globals.browser,
        },
    },
    {
        plugins: {
            '@next/next': fixupPluginRules(nextPlugin),
        },
        rules: {
            ...nextPlugin.configs.recommended.rules,
            ...nextPlugin.configs['core-web-vitals'].rules,
        },
    },
    {
        // TEMP: until all sources got fixed
        rules: { '@typescript-eslint/no-explicit-any': 'off' },
    },
    prettierConfigRecommended,
    {
        files: ['**/*.{jsx,tsx}'],
        plugins: {
            react: fixupPluginRules(reactPlugin),
        },
        settings: { react: { version: 'detect' } },
        rules: {
            ...reactPlugin.configs.recommended.rules,
            // TEMP: code needs adoptions: React must be in scope?!
            'react/react-in-jsx-scope': 0,
            //
            //currently difficult at some places..., e.g. params props
            // TODO reenable later
            'react/prop-types': 0,
        },
    },
    {
        // TEMP code will need adoptions:
        rules: {
            'no-undef': 1,
            'no-console': 0,
        },
    },
    {
        plugins: { 'react-hooks': fixupPluginRules(reactHooks) },
        rules: {
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'error',
        },
    },
    {
        ignores: [
            '**/node_modules',
            '**/public',
            '**/build',
            // generated by chakra-ui, so if problematic...
            // 'components/ui/',
            '.next/**',
            '.yarn',
        ],
    },
];
